// src/pages/MainPage.tsx
import React from 'react';

const MainPage = () => (
  <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-green-50 to-blue-50 px-4">
    <div className="text-center max-w-4xl mx-auto">
      <h1 className="text-5xl md:text-6xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-green-600 to-blue-600 mb-6">
        GreenWear
      </h1>
      <h2 className="text-2xl md:text-3xl font-bold text-gray-800 mb-4">
        실시간 건강 모니터링
      </h2>
      <p className="text-lg md:text-xl text-gray-600 mb-8 leading-relaxed">
        웨어러블 센서와 AI로 건강 상태를 실시간으로 확인하세요.<br />
        옷의 색상으로 건강 상태를 시각적으로 표현합니다.
      </p>
      
      <div className="grid md:grid-cols-3 gap-6 mt-12">
        <div className="bg-white rounded-lg shadow-lg p-6 hover:shadow-xl transition-shadow duration-300">
          <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4 mx-auto">
            <div className="w-6 h-6 bg-green-500 rounded-full"></div>
          </div>
          <h3 className="text-lg font-semibold text-gray-800 mb-2">정상 상태</h3>
          <p className="text-gray-600">건강한 상태일 때 초록색으로 표시됩니다</p>
        </div>
        
        <div className="bg-white rounded-lg shadow-lg p-6 hover:shadow-xl transition-shadow duration-300">
          <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center mb-4 mx-auto">
            <div className="w-6 h-6 bg-yellow-500 rounded-full"></div>
          </div>
          <h3 className="text-lg font-semibold text-gray-800 mb-2">경고 상태</h3>
          <p className="text-gray-600">주의가 필요할 때 노란색으로 표시됩니다</p>
        </div>
        
        <div className="bg-white rounded-lg shadow-lg p-6 hover:shadow-xl transition-shadow duration-300">
          <div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center mb-4 mx-auto">
            <div className="w-6 h-6 bg-red-500 rounded-full"></div>
          </div>
          <h3 className="text-lg font-semibold text-gray-800 mb-2">응급 상태</h3>
          <p className="text-gray-600">즉시 대응이 필요할 때 빨간색으로 표시됩니다</p>
        </div>
      </div>
    </div>
  </div>
);

export default MainPage;

// frontend/src/pages/MainPage.vue
<template>
  <div>
    <!-- 페이지 헤더 -->
    <div class="text-center mb-12">
      <div class="inline-flex items-center px-6 py-3 bg-white/60 backdrop-blur-sm rounded-2xl shadow-lg border border-white/20 mb-6">
        <span class="text-2xl mr-3">🩺</span>
        <h2 class="text-3xl font-bold bg-gradient-to-r from-green-600 to-blue-600 bg-clip-text text-transparent">
          GreenWear 생체신호 모니터링 시스템
        </h2>
      </div>
      <p class="text-gray-600 text-lg max-w-2xl mx-auto">
        의료진과 군인들을 위한 실시간 생체신호 모니터링 및 상태 분류 시스템
      </p>
    </div>

    <!-- 컨텐츠 그리드 -->
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-8">
      <!-- 왼쪽 사이드바: VitalsCard -->
      <div class="xl:col-span-1">
        <div class="sticky top-24">
          <Suspense>
            <template #default>
              <VitalsCard />
            </template>
            <template #fallback>
              <div class="bg-white/80 backdrop-blur-sm rounded-2xl shadow-lg border border-white/20 p-8 text-center">
                <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-green-600 mx-auto mb-4"></div>
                <p class="text-gray-600">Vitals 시스템 로딩 중...</p>
              </div>
            </template>
          </Suspense>
        </div>
      </div>
      
      <!-- 메인 컨텐츠: VitalsLive -->
      <div class="xl:col-span-2">
        <Suspense>
          <template #default>
            <VitalsLive />
          </template>
          <template #fallback>
            <div class="bg-white/80 backdrop-blur-sm rounded-2xl shadow-lg border border-white/20 p-8 text-center">
              <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
              <p class="text-gray-600">실시간 모니터링 시스템 로딩 중...</p>
            </div>
          </template>
          </Suspense>
      </div>
    </div>
    
    <!-- 하단 정보 섹션 -->
    <div class="mt-16 text-center">
      <div class="bg-white/60 backdrop-blur-sm rounded-2xl shadow-lg border border-white/20 p-8">
        <h3 class="text-xl font-semibold text-gray-800 mb-4">🚀 GreenWear 시스템 정보</h3>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 text-sm text-gray-600">
          <div>
            <div class="text-2xl mb-2">🩺</div>
            <div class="font-medium text-gray-800">실시간 모니터링</div>
            <div>24/7 생체신호 추적</div>
          </div>
          <div>
            <div class="text-2xl mb-2">🎯</div>
            <div class="font-medium text-gray-800">정확한 분류</div>
            <div>AI 기반 상태 분석</div>
          </div>
          <div>
            <div class="text-2xl mb-2">⚡</div>
            <div class="font-medium text-gray-800">빠른 응답</div>
            <div>즉시 알림 시스템</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import VitalsCard from '../components/VitalsCard.vue'
import VitalsLive from '../components/VitalsLive.vue'

// KeepAlive에서 사용할 컴포넌트 이름
defineOptions({
  name: 'MainPage'
})
</script>

<style scoped>
/* 기본 스타일 */
</style>
